config/routes.rb
SrBujInAction::Application.routes.draw do
  root to: 'example/lists#index'

  namespace :example do
    resources :lists do
      resources :tasks
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :done_at

  validates :name, presence: true

  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :content

  validates :content, presence: true

  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/example/dummy_controller.rb
class Example::DummyController < ApplicationController
  layout 'dummy'

end

app/controllers/example/lists_controller.rb
class Example::ListsController < Example::DummyController
  before_filter :get_list, only: [ :show, :edit, :update, :destroy ]

  def index
    @lists = List.all
  end

  def show
    @tasks = @list.tasks
    respond_to do |format|
      format.html
      format.js { render partial: 'show', content_type: 'text/html' }
    end
  end

  def new
    @list = List.new
    render partial: 'new', content_type: 'text/html'
  end

  def edit
    render partial: 'edit', content_type: 'text/html'
  end

  def create
    @list = List.new params[:list]
    if @list.save
      js_notify message: t('app.created', model: @list.class)
      render partial: @list, content_type: 'text/html'
    else
      js_notify message: t('app.error')
      render partial: 'new', status: :unprocessable_entity
    end
  end

  def update
    if @list.update_attributes params[:list]
      js_notify message: t('app.updated', model: @list.class)
      render partial: @list, content_type: 'text/html'
    else
      js_notify message: t('app.error')
      render partial: 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    js_redirect(to: example_lists_path)
  end

  private
    def get_list
      @list = List.find params[:id]
    end
end

app/controllers/example/tasks_controller.rb
class Example::TasksController < Example::DummyController
  before_filter :get_list, only: [ :edit, :create, :update, :destroy ]
  before_filter :get_task, only: [ :edit, :update, :destroy ]

  def edit
    render partial: 'edit', content_type: 'text/html'
  end

  def create
    @task = @list.tasks.new params[:task]
    if @task.save
      js_notify message: t('app.created', model: @task.class)
      render partial: @task, content_type: 'text/html'
    else
      js_notify message: t('app.error')
      render partial: 'form', status: :unprocessable_entity
    end
  end

  def update
    if @task.update_attributes params[:task]
      js_notify message: t('app.updated', model: @task.class)
      render partial: @task, content_type: 'text/html'
    else
      js_notify message: t('app.error')
      render partial: 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    render nothing: true, content_type: 'text/html'
  end

  private
    def get_task
      @task = @list.tasks.find params[:id]
    end

    def get_list
      @list = List.find params[:list_id]
    end
end

app/controllers/example/todos_controller.rb
class Example::TodosController < Example::DummyController
  before_filter :get_list, only: [ :edit, :create, :update, :destroy ]
  before_filter :get_todo, only: [ :edit, :update, :destroy ]

  def edit
    render partial: 'edit', content_type: 'text/html'
  end

  def create
    @todo = @list.todos.new params[:todo]

    if @todo.save
      js_notify message: t('app.created', model: @todo.class)
      render partial: @todo, content_type: 'text/html'
    else
      js_notify message: t('app.error')
      render partial: 'form', status: :unprocessable_entity
    end
  end

  def update
    if @todo.update_attributes params[:todo]
      js_notify message: t('app.updated', model: @todo.class)
      render partial: @todo, content_type: 'text/html'
    else
      js_notify message: t('app.error')
      render partial: 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy

    render nothing: true, content_type: 'text/html'
  end

  private
    def get_todo
      @todo = @list.todos.find params[:id]
    end

    def get_list
      @list = List.find params[:list_id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object, field)
    if object && object.errors[field].any?
      content_tag(:span, object.errors[field].to_sentence, class: 'help-inline error')
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/example/lists/_edit.haml
.modal
  .modal-header
    %h2 Editing list
  .modal-body
    = form_for @list, url: polymorphic_path([ :example, @list ]), html: { class: 'form-horizontal', data: { remote: true, target: dom_id(@list), modal: true, error: 'modal', respond_as: :put } } do |f|
      .control-group
        = f.label :name, class: 'control-label'
        .controls
          = f.text_field :name, class: 'input', autofocus: true
          = errors_for(@list, :name)
  .modal-footer
    .btn{data: { dismiss: 'modal' }}= t('app.close')

app/views/example/lists/_list.haml
= content_tag_for(:tr, list) do
  %td= link_to list.name, example_list_path(list), data: { remote: true, target: 'content', push: true }
  %td= link_to 'Edit', edit_example_list_path(list), data: { remote: true, target: 'modal', modal: true }

app/views/example/lists/_new.haml
.modal
  .modal-header
    %h2 New list
  .modal-body
    = form_for @list, url: polymorphic_path([ :example, @list ]), html: { class: 'form-horizontal', data: { remote: true, target: 'lists', modal: true, error: 'modal' } } do |f|
      .control-group
        = f.label :name, class: 'control-label'
        .controls
          = f.text_field :name, class: 'input', autofocus: true
          = errors_for(@list, :name)
  .modal-footer
    .btn{data: { dismiss: 'modal' }}= t('app.close')

app/views/example/lists/_show.haml
%h2
  = @list.name
  .pull-right
    = link_to 'Destroy', example_list_path(@list), data: { remote: true, confirm: 'Are you sure?', method: :delete }

= render partial: 'example/tasks/form'

%table#tasks.table
  %thead
    %tr
      %th Task
      %th
  %tbody
    = render @tasks

app/views/example/lists/index.haml
%h1 Listing lists

%table#lists.table
  %thead
    %tr
      %th List
      %th
  %tbody
    = render @lists
%br
= link_to 'New List', new_example_list_path, class: 'btn btn-primary pull-right', data: { remote: true, target: 'modal', modal: true }

app/views/example/lists/show.haml
= render partial: 'show'

app/views/example/tasks/_edit.haml
.modal
  .modal-header
    %h2 Editing tasks
  .modal-body
    = form_for @task, url: polymorphic_path([:example, @list, @task]), html: { class: 'form-horizontal', data: { remote: true, target: dom_id(@task), modal: true, error: 'modal', respond_as: :put } } do |f|
      .control-group
        = f.label :content, class: 'control-label'
        .controls
          = f.text_field :content, class: 'input', autofocus: true
          = errors_for(@task, :conten)
  .modal-footer
    .btn{data: { dismiss: 'modal' }}= t('app.close')

app/views/example/tasks/_form.haml
= form_for Task.new, url: example_list_tasks_path(@list), html: { class: 'form-horizontal', data: { remote: true, target: 'tasks', error: 'new_todo' } } do |f|
  .control-group
    = f.label 'Task to Do', class: 'control-label'
    .controls
      = f.text_field :content, class: 'input', autofocus: true
      = errors_for(@task, :content)

app/views/example/tasks/_task.haml
= content_tag_for(:tr, task) do
  %td= task.content
  %td= link_to 'Edit', edit_example_list_task_path(@list, task), data: { remote: true, target: 'modal', modal: true }
  %td= link_to 'Destroy', example_list_task_path(@list, task), data: { remote: true, target: dom_id(task), confirm: 'Are you sure?', method: :delete }

app/views/example/todos/_edit.haml
.modal
  .modal-header
    %h2 Editing todo
  .modal-body
    = form_for @todo, url: polymorphic_path([:example, @list, @todo]), html: { class: 'form-horizontal', data: { remote: true, target: dom_id(@todo), modal: true, error: 'modal', respond_as: :put } } do |f|
      .control-group
        = f.label :content, class: 'control-label'
        .controls
          = f.text_field :content, class: 'input', autofocus: true
          = errors_for(@todo, :conten)
  .modal-footer
    = link_to_function t('app.close'), "$('#modal').modal('toggle');", class: 'btn'

app/views/layouts/application.haml
!!!
%html
  %head
    %title SrBujInAction
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to 'SrBuj', root_path, class: 'brand'
    #content.container.well
      = yield
  #modal
  = javascript_include_tag 'application'

app/views/layouts/dummy.haml
!!!
%html
  %head
    %title SrBujInAction
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to 'SrBuj', root_path, class: 'brand'
    #content.container.well
      = yield
  #modal
  = javascript_include_tag 'application'